### ISSUE TITLE
Dataset.to_array method

### ISSUE THREAD

**Issue by shoyer** [xray/xray#132]
It should be possible to easily convert back and forth between Datasets and DataArrays that consist of each variable in a Dataset stacked along a "variable" dimension.

The implementation for `to_array` should be mostly equivalent to `DataArray.from_series(ds.to_dataframe().stack())`, although for performance reasons we probably don't actually want to convert everything into intermediate representations as pandas object.

Similarly, `to_dataset(dimension)` would be roughly equivalent to `Dataset.from_dataframe(array.to_series().stack(dimension))`.

**Comment by shoyer** [comment]
`DataArray.to_dataset()` currently converts a DataArray into a Dataset with a single data variable.

This is fine, but we should add a `dim` argument so that `x.to_dataset(dim='time')` will instead create a Dataset with one data variable per time value.

**Comment by IamJeffG** [comment]
`Dataset.to_array` will have to decide how to handle attributes on the separate Variables being stacked.  For consistency we should keep all or drop all.  The latter is far simpler.

**Comment by shoyer** [comment]
Agreed. +1 for dropping attributes.
