### ISSUE TITLE
Plot methods

### ISSUE THREAD

**Issue by shoyer** [xray/xray#185]
It would be awesome to have built in plot methods, similar to `pandas.DataFrame.plot` and `pandas.Series.plot`.

Although we could just copy the basic plotting methods from pandas, the strongest need is for cases where there is no corresponding plot methods.

Notably, we should have shortcut methods for plotting 2-dimensional arrays with labels, corresponding to matplotlib's contour/contourf/imshow/pcolormesh. If we include an axis argument, such an API should even suffice for plotting data on a map via [cartopy](http://scitools.org.uk/cartopy/docs/latest/matplotlib/intro.html), although it wouldn't hurt to add some optional keyword arguments shortcuts (e.g., `proj='orthographic'`).

**Comment by clarkfitzg** [comment]
Starting on this now. Some more relevant notes:

xray + matplotlib
Wrap matplotlib using xray metadata
wrap matplotlib methods directly but label axes with xray metadata automatically.  Just like pandas plot method. Ideally, this should use plot submethods like x.plot.contourf() or x.plot_contourf(), similar to plans for pandas.

Grid 2D images easily
Given a 3D DataArray, "group by" one dimension on which to show the remaining 2D image for each tick.  These images can simply be wrapped, as in ggplot's facet_wrap.

lower priority: given an nd DataArray, facet_grid on multiple dimensions, showing 2D images on each.

For API inspiration, consider seaborn’s FacetGrid.

**Comment by nbren12** [comment]
As a user, I am very excited in this work. I just wanted to mention a library called [holoviews](http://ioam.github.io/holoviews/) that seems to implement an very similar set of features as xray with a focus on visualization. It seems that the API from that project is very well suited to plotting higher dimensional data. I also posted about this in the xray google group, but it seems like there is not much traffic there.

**Comment by clarkfitzg** [comment]
@nbren12 Thanks for the input! I'll add a link to that library in the docs.

By the way, development is happening on this branch now: https://github.com/xray/xray/tree/feature-plotting

**Comment by nbren12** [comment]
I've been watching the progress on that branch haha. exciting stuff!

**Comment by shoyer** [comment]
something to consider: we should make sure we can handle NaNs properly (by converting to masked array).

**Comment by clarkfitzg** [comment]
@shoyer good point- I hadn't yet considered that.

**Comment by clarkfitzg** [comment]
Closed by #466
