### ISSUE TITLE
Proposal: allow tuples instead of slice objects in sel or isel

### ISSUE THREAD

**Issue by shoyer** [xray/xray#280]
e.g., we should be able to write `ds.sel(time=('2000', '2010'))` as an alias for `ds.sel(time=slice('2000', '2010'))`

**Comment by IamJeffG** [comment]
I agree with your concerns and vote "-1" on this proposal.

When I read `ds.sel(time=('2000', '2010'))` with no outside context, I expect to get back exactly two ticks along the time axis: that equal to '2000' and that equal to '2010'.

**Comment by shoyer** [comment]
OK, closing.

The real fix here will require new Python syntax to support `ds[time='2000':'2010']`
