### ISSUE TITLE
xray.concat incorrectly converts string arrays to numeric dtype

### ISSUE THREAD

**Issue by currivan** [xray/xray#305]
String DataArrays containing mostly representations of numbers are converted to int or float during concatenation, even when they contain non-convertible values.

a = xray.DataArray(np.arange(6).reshape(3, 2).astype(str), dims=['x','y'])
b = xray.DataArray(np.arange(12).reshape(3, 4).astype(str), dims=['x','y'])

a.dtype, b.dtype
Out:
(dtype('S21'), dtype('S21'))

a[0,0] = 'foo'
a
Out: <xray.DataArray (x: 3, y: 2)>
array([['foo', '1'],
       ['2', '3'],
       ['4', '5']], 
      dtype='|S21')
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1

xray.concat([a,b], dim='y')
Out:
<xray.DataArray (x: 3, y: 6)>
array([[ nan,   1.,   0.,   1.,   2.,   3.],
       [  2.,   3.,   4.,   5.,   6.,   7.],
       [  4.,   5.,   8.,   9.,  10.,  11.]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1 0 1 2 3

Why is this converted to float, with non-convertible strings mapped to nan? Without setting the 'foo' value, the result is an int array.

The same problem happens when directly calling the inner functions:
xray.Dataset._concat([a._dataset, b._dataset], dim='y')[None]
and
xray.Variable.concat([a._dataset._arrays[None], b._dataset._arrays[None]], 'y')

**Comment by shoyer** [comment]
Thanks for the report!

This has been fixed on master and will be in the next release.
