### ISSUE TITLE
Alternatives to virtual variables in the form "time.season"?

### ISSUE THREAD

**Issue by shoyer** [xray/xray#345]
@jhamman writes in #337:

> Since `ds.groupby('time.season').mean('time')` returns a Dataset with a Coordinates variable named `time.season`, `ds.sel(time.season='JJA')` doesn't work for Python syntax reasons. So, I don't know if I would change the syntax used in my example (selecting my position). I'm not keen on this constructor: `ds.sel(**{'time.season':'JJA'})`. I'm wondering if it would be better to name the coordinates returned from "virtual variable" operations without the "time." portion. Just a thought.

I agree, this is awkward. This has been on my to-do list in the back of my head for some time. 

My hesitation with just using `'season'` for the name of `ds['time.season']` is that it would be a little weird to have indexing return something with a different name than what you asked for.

`ds['season']` is another optional that initially looks even more appealing, but what if we have more than datetime variable? This is not unheard of (e.g., 'time' and 'forecast_reference_time').

Another option would be to simply support `ds['time_season']`. Then at least you can do indexing without using `**` (e.g., `ds.sel(time_season='JJA')`).

**Comment by shoyer** [comment]
After some contemplation, I think it's actually OK to switch to the result of `ds['time.season']` to being a DataArray with the name `'season'`. The use of `.` is already an indicator that something special is going on. I'll switch this for v0.4.

**Comment by jhamman** [comment]
Looks good @shoyer.  This is what I would have suggested.

**Comment by shoyer** [comment]
:)

@jhamman FWIW, I think we've one bug fix and a few documentation tweaks (including yours) away from being ready to release v0.4.
