### ISSUE TITLE
Set coordinate resolution in ds.to_netcdf

### ISSUE THREAD

**Issue by naught101** [xray/xray#374]
I am trying to mutate some netcdf data, so that I can feed it to a Fortran model, but the `ds.to_netcdf` function results in a file with different time units (minutes instead of seconds).

Original file:
```
$ ncdump -h ~/path/to/met_forcings.nc
netcdf met_forcings {
dimensions:
        x = 1 ;
        y = 1 ;
        time = UNLIMITED ; // (70128 currently)
        z = 1 ;
variables:
        ...
        double time(time) ;
                time:units = "seconds since 2002-01-01 00:30:00" ;
```

New file: 
```
$ ncdump -h ../projects/synthetic_forcings/data/tumba_site_mean_2_year.nc 
netcdf tumba_site_mean_2_year {
dimensions:
        time = 35088 ;
        y = 1 ;
        x = 1 ;
        z = 1 ;
variables:
        ...
        float time(time) ;
                time:calendar = "proleptic_gregorian" ;
                time:units = "minutes since 2000-01-01 00:30:00" ;
```

The model is expecting second units, so all of the time-based calculations are amusingly out of whack. In my case, the Fortran model is probably to blame, because it's time reading function should be more robust. However, it would be generally useful to be able to specify the time units when saving to netcdf. I can't see a way of doing that currently.

**Comment by shoyer** [comment]
This is actually already implemented but poorly documented. See the section on DataArray encoding: http://xray.readthedocs.org/en/stable/io.html#netcdf

Basically, you just need to add a units encoding to the time variable with the desired time units.

**Comment by naught101** [comment]
Ah, cool, that looks good, however, I think there might be a bug somewhere. Here's what I was getting originally:

```
In [62]: new_data['time'].encoding

Out[62]: {}

In [60]: new_data.to_netcdf('data/tumba_site_mean_2_year.nc')
```
resulted in:
```
$ ncdump ../projects/synthetic_forcings/data/tumba_site_mean_2_year.nc|grep time --context=2
netcdf tumba_site_mean_2_year {
dimensions:
        time = 35088 ;
        y = 1 ;
        x = 1 ;
variables:
        ...
        float time(time) ;
                time:calendar = "proleptic_gregorian" ;
                time:units = "minutes since 2000-01-01 00:30:00" ;
...

 time = 0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360, 390, 420, 
    450, 480, 510, 540, 570, 600, 630, 660, 690, 720, 750, 780, 810, 840, 
```

And if I copy the encoding from the original file, as it was loaded:
```
In [65]: new_data['time'].encoding = data['time'].encoding

In [66]: new_data['time'].encoding

Out[66]: {'dtype': dtype('>f8'), 'units': 'seconds since 2002-01-01 00:30:00'}

In [67]: new_data.to_netcdf('data/tumba_site_mean_2_year.nc')
```
results in
```
$ ncdump ../projects/synthetic_forcings/data/tumba_site_mean_2_year.nc|grep time --context=1
dimensions:
        time = 35088 ;
        y = 1 ;
--
variables:
        ...
        double time(time) ;
                time:calendar = "proleptic_gregorian" ;
                time:units = "seconds since 2002-01-01T00:30:00" ;

...
 time = -63158400, -63156600, -63154800, -63153000, -63151200, -63149400, 
    -63147600, -63145800, -63144000, -63142200, -63140400, -63138600, 
```

Now the units are right, but the values are way off. I can't see anything obvious missing from the encoding, compared to the xray docs, but I'm not sure how it works.

Also, since seconds are the base SI unit for time, I think it would be sensible to use seconds by default, if no encoding is given.

**Comment by naught101** [comment]
blegh... just noticed the different dates. Never mind :P

**Comment by shoyer** [comment]
By default we use the biggest units that divide all the given times equally. That's not necessarily SI, but it does result in more interpretable time values....
