### ISSUE TITLE
DataArray and virtual variables

### ISSUE THREAD

**Issue by mathause** [xray/xray#388]
Now that we are at it... Why don't DataArrays have virtual variables?

**Comment by shoyer** [comment]
The short answer: they do have virtual variables, just not a `virtual_variables` attribute:
```
import pandas as pd
import numpy as np
import xray
t = pd.date_range('2000-01-01', '2000-12-31', freq='6H')
x = np.random.rand(*t.shape)
time = xray.DataArray(t, name='t', dims='time')
print time['time.month']
```
```
<xray.DataArray 'month' (time: 1461)>
array([ 1,  1,  1, ..., 12, 12, 12], dtype=int32)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-01T06:00:00 2000-01-01T12:00:00 ...
```

I actually recently removed the `virtual_variables` attribute from `Dataset` on the development version. A cleaner way to handle virtual variables would be to add a `.dt` attribute like pandas, e.g., `time.dt.month`. That would also support discovery (e.g., `time.dt.<tab>` or `ds.time.dt.<tab>`) better than a special attribute to list permissible strings.

**Comment by mathause** [comment]
Ok, thanks - it seems I didn't even try :P

I find the name virtual_variables easier to grasp than dt, but better to be consistent with panda.
