### ISSUE TITLE
Segfault on import

### ISSUE THREAD

**Issue by naught101** [xray/xray#404]
Using xray 0.4.0 from binstar:

```
python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:03:53) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xray
[1]    21893 segmentation fault (core dumped)  python
```

This is in a conda env, which was transferred from a previous incarnation of this computer (crash+burn -> reinstall), so maybe there's something wrong with the installation. I've tried re-installing xray from binstar. I don't really know what else to try. Any ideas?

**Comment by naught101** [comment]
Other envs aren't affected. I guess this is a conda problem, not an xray problem. Easy enough to re-create an env, I guess.

**Comment by shoyer** [comment]
Yikes! I'm guessing the problem is an xray dependency that we import internally, likely netCDF4-Python (or maybe numpy or scipy?). Xray itself is pure Python, so getting a set fault would be quite surprising.
