### ISSUE TITLE
millisecond and microseconds support

### ISSUE THREAD

**Issue by jsignell** [xray/xray#406]
netcdf4python supports milliseconds and microseconds:

https://github.com/Unidata/netcdf4-python/commit/22d439d6d3602171dc2c23bca0ade31d3c49ad20

would it be possible to support in X-ray?

**Comment by shoyer** [comment]
Sure, this is pretty easy to add. Should make it into the next release.

**Comment by jhamman** [comment]
As a small side note, netcdf4-python doesn't exactly support microseconds.  There is a known precision issue that ends up giving `netcdftime` a minimum time precision of seconds: https://github.com/Unidata/netcdf4-python/issues/321

**Comment by shoyer** [comment]
We use numpy's datetime64 machinery instead of netcdftime when possible, so at least for the standard/gregorian calendar this might actually be OK.

**Comment by jhamman** [comment]
My thoughts exactly.  The original post mentioned `netcdftime` so I thought it would be beneficial to point that out.  For standard calendards using Python/Numpy datetime objects, microsecond precision is preserved.

**Comment by shoyer** [comment]
There's also leap seconds, and I'm pretty sure that none of the underlying libraries here handle those properly.
