### ISSUE TITLE
Nearest neighbor lookups

### ISSUE THREAD

**Issue by mathause** [xray/xray#415]
Nearest neighbor lookups does not seem to work:

    import xray
    xray.__version__

0.4.1

    data = xray.DataArray([1, 2, 3], dims='x')
    data.sel(x=[1.1, 1.9], method='nearest')

ValueError: not all values found in index 'x'

Example from:
http://xray.readthedocs.org/en/latest/indexing.html#nearest-neighbor-lookups

(pandas version 0.16.1)

**Comment by shoyer** [comment]
This feature has not yet appeared in the released version of xray.

"latest" is the development documentation -- in this case for xray 0.5, which I expect to release today (if I can resolve a few final issues with the documentation)

"stable" is the latest public release. This is where you get by default from http://xray.readthedocs.org

**Comment by shoyer** [comment]
Just pushed xray 0.5 to pypi. You can get it with pip: `pip install -U xray`

**Comment by mathause** [comment]
ok great - thanks
