### ISSUE TITLE
Automatically decode netCDF data to native endianness

### ISSUE THREAD

**Issue by shoyer** [xray/xray#416]
Unfortunately, netCDF3 is big endian, but most modern CPUs are little endian.

Cython requires that data match native endianness in order to perform operations. This means that users can get strange errors when performing aggregations with bottleneck or after converting an xray dataset to pandas.

It would be nice to handle this automatically as part of the "decoding" process. I don't think there are any particular advantages to preserving non-native endianness (except, I suppose, for serialization back to another netCDF3 file). My understanding is that most calculations require native endianness, anyways.

CC @bareid

**Comment by bareid** [comment]
Thanks for posting, Stephan!  I'm interested in assisting with a possible enhancement!  Here's a quick wrapper I wrote to deal with this issue in my code:

```python
def wrap_open_dataset(fname, verbose=False):
    """
    Forces switch to native endianness when dataset is read in so
    that endian-dependent functions (e.g., nanmin from bottleneck)
    will always work.
    Note that ec2 and my mac are little endian, but only ec2 was
    broken with a
    "ValueError: Big-endian buffer not supported on little-endian
    compiler."
    """
    ds = xray.open_dataset(fname)
    all_vars = ds.coords.keys() + ds.data_vars.keys()
    dilist = []
    for kk in all_vars:
        di = ds[kk].dtype
        dnew = di.newbyteorder('N')
        ds[kk].values = ds[kk].values.astype(dnew, casting='equiv', copy=False)
        df = ds[kk].dtype
        if verbose is True:
            dilist.append(di)
    if verbose is True:
        for kk, di in zip(all_vars, dilist):
            df = ds[kk].dtype
            print 'converted', di, 'to', df
    return ds
```
