### ISSUE TITLE
include data for 'Calculating Seasonal Averages ... ' Example

### ISSUE THREAD

**Issue by shabbychef** [xray/xray#424]
The example [Calculating Seasonal Averages ... ](https://github.com/xray/xray/blob/master/doc/examples/monthly-means.rst) is apparently impossible to replicate without access to the datafile ```R1002RBRxaaa01a.vic.hmm.197909-201212.nc```. A google search does not find such a file, nor does it appear to be in the xray repo. The example is considerably less useful if the novice cannot 'follow along at home'.  (I realize that sharing the data may require some legal gymnastics; perhaps a simpler example--with faked data, say--would suffice.)

**Comment by jhamman** [comment]
@shoyer.  I'm not sure you want to carry around any more datasets but I can certainly provide a sample dataset for this example if you want.

**Comment by shoyer** [comment]
@jhamman how big is your data? It would indeed be nice to host this online somewhere.

**Comment by jhamman** [comment]
That particular dataset is ~5GB but I could cut it down to a more reasonable size.

**Comment by shoyer** [comment]
If you can cut it down to something like 50-100 MB (obviously smaller is
better) we can host it on github. I'll make another xray repo for example
datasets.

**Comment by jhamman** [comment]
Yes, can do.  It will take me a bit of time to get around to it but you can assign this issue to me.
Just let me know when you have an data repository setup.

**Comment by shoyer** [comment]
@jhamman see https://github.com/xray/xray-data

**Comment by shabbychef** [comment]
thanks much!
