### ISSUE TITLE
Add rolling mean function

### ISSUE THREAD

**Issue by DamienIrving** [xray/xray#447]
A nice addition to the [time-series functionality](http://xray.readthedocs.org/en/stable/time-series.html) that is built into xray would be the ability to calculate a rolling mean (e.g. for those cases where you've got daily data but you want to work on the 10-day running mean or something).

As far as I'm aware (apologies if I'm wrong), to do a rolling mean at the moment you have to convert to a pandas DataFrame, used the pandas [`rolling_mean()`](http://pandas.pydata.org/pandas-docs/stable/computation.html#moving-rolling-statistics-moments) function and then convert back to an xray data array. This is fine for one dimensional data, but not so nice when you want to do it over a large (time, lat, lon) array.

**Comment by shoyer** [comment]
I agree, this would be very nice. Contributions in this area would be very welcome.

The easy way to do this would be by wrapping [bottleneck](https://github.com/kwgoodman/bottleneck):
https://github.com/xray/xray/issues/130

Bottleneck is also pretty easy to use on its own. To adapt it for xray, it would mostly be a matter of converting the `axis` argument to `dim`.

**Comment by shoyer** [comment]
closing this in favor of #130.
