### ISSUE TITLE
asarray Compatibility

### ISSUE THREAD

**Issue by mcdevitts** [xray/xray#448]
To "numpify" a function, usually asarray is used:

def db2w(arr):
    return 10 ** (np.asarray(arr) / 20.0)

Now you could replace the divide with np.divide, but it seems much simpler to use np.asarray. Unfortunately, if you use any function that has been "vectorized," it will only return the values of the DataArray as an ndarray. This strips the object of any "xray" meta-data and severely limits the use of this class. It requires that any function that wants to work seamlessly with a DataArray explicitly check that it's an instance of DataArray

This seems counter-intuitive to the numpy framework where any function, once properly vectorized, can work with python scalars (int, float) or list types (tuple, list) as well as the actual ndarray class. It would be awesome if code that worked for these cases could just work for DataArrays.

**Comment by shoyer** [comment]
Unfortunately, there's no way to make `np.asarray` return anything other than a numpy array without metadata -- that's kind of the entire point of `asarray`.

We do have some other options, though. The first two already work:

- use `xray.Dataset.apply` to call a function, e.g., `ds.apply(db2w)`
- write a numpy universal function using numba:

    ```python
    @numba.vectorize
    def db2w(arr):
        return 10 ** (arr / 20.0)
    ```
 
- we could write a modified version of `asarray` that passes through xray objects
- we could write a decorator that transforms a function to preserve/restore xray metadata, e.g.,

    ```python
    def keep_metadata(func):
        def wrapper(array, **kwargs):
            return array.__array_wrap__(func(array))
        return wrapper

    @keep_metadata
    def db2w(arr):
        return 10 ** (np.asarray(arr) / 20.0)
    ```

**Comment by mcdevitts** [comment]
I agree that it's the point with np.asarray, but given the implementation you'd think np.asanyarray would work. My initial takeaway (until examining the source) was that this was an ndarray with additional attributes and properties. Perhaps, I'm leaning too far towards numpy and too far away from pandas.

As background: my usage involves RF pattern data which typically involves a lot of independent variables to lug around as well as the measured data.

I'll look into your other suggestions. Thank you for your reply.

**Comment by shoyer** [comment]
Xray doesn't use numpy ndarray subclasses, mostly because that would tie our underlying array implementations to numpy and stop us from using interesting alternative array implementations like [dask](http://dask.pydata.org/en/latest/array.html). Hence, `np.asanyarray` does not work either.
