### ISSUE TITLE
Conventions decoding should properly handle byte type attributes on Python 3

### ISSUE THREAD

**Issue by shoyer** [xray/xray#451]
This only appears with the h5netcdf backend (for now), because netCDF4-python decodes all string attributes to unicode on Python 3.

We might also fix this upstream in h5netcdf by copying this behavior from netCDF4-python.

xref https://github.com/xray/xray/issues/444#issuecomment-117993960

**Comment by razvanc87** [comment]
Yes, I think that this should be implemented in `h5netcdf` (possibly `h5py`? because `h5netcdf` depends on `h5py` I belive)
