### ISSUE TITLE
Read NetCDF files with multiple values in missing_value attribute

### ISSUE THREAD

**Issue by jjhelmus** [xray/xray#471]
For certain data, for example NEXRAD Level 2 data, the NetCDF Java library will set the missing_value attribute for multiple variables in the produced NetCDF to a vector containing multiple variables.  Currently loading these files in xray raises a ValueError in the `decode_cf_variable function`.

Netcdf4-python returns a NumPy masked array with all values in the missing_value vector to np.ma.masked, xray may want to copy this model by replacing these elements with NaN.  Another option is to raise an more appropriate error indicating that these files are not supported as vector missing_value attributes do not seem to meet a strict reading of [section 2.5.1 of the CF conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#missing-data).

I can provide an example file if desired.

**Comment by shoyer** [comment]
You can still read these files if you set mask_and_scale=False in open_dataset -- it just won't decode the missing values for you.

Arguably, we should raise an error message saying just that.

From a practical perspective, are you interested in the different types of these missing values? Presumably there is some reason why they were coded differently in the first place.

**Comment by jjhelmus** [comment]
Yes, the two values in the missing_value attribute indicate two classes of data (not collected vs below minimum detectable threshold) and these data can be access by setting mask_and_scale=False but this also results in a valid data being returned without scaling which makes it less useful.  

My question is how should xray should handle these cases?  Either replace all instances of the values in missing_value with NaN or raise a error message stating that multiple missing_values are not supported similar?  I'd be happy to create a PR implementing either case.

**Comment by shoyer** [comment]
What about issuing a warning, and then decoding the duplicate values to NaN anyways? I'm usually not a fan of warnings, but my guess is that this would be the most helpful behavior for users.

**Comment by jjhelmus** [comment]
Sounds like a good solution.  I'll work on a PR.

**Comment by shoyer** [comment]
Awesome, thanks!

This is where you'll find the decoding logic:
https://github.com/xray/xray/blob/v0.5.2/xray/conventions.py#L663
