### ISSUE TITLE
to_netcdf failing for datasets with a single time value

### ISSUE THREAD

**Issue by rsignell-usgs** [xray/xray#476]
In this notebook: http://nbviewer.ipython.org/gist/rsignell-usgs/047235496029529585cc, the 
`ds.to_netcdf` method in cell [12] is failing for this dataset with a single time value:
```
/home/usgs/miniconda/envs/ioos/lib/python2.7/site-packages/xray/conventions.pyc in infer_datetime_units(dates)
    185     unique_timedeltas = np.unique(np.diff(dates[pd.notnull(dates)]))
    186     units = _infer_time_units_from_diff(unique_timedeltas)
--> 187     return '%s since %s' % (units, pd.Timestamp(dates[0]))
    188 
    189 

IndexError: too many indices for array
```
When there is a single value, I guess `dates` must not be an array.

**Comment by shoyer** [comment]
Thanks for the report. I believe this is fixed on master: https://github.com/xray/xray/pull/454 (I hope to get a release out shortly)

**Comment by rsignell-usgs** [comment]
Indeed, with master, it's working.
http://nbviewer.ipython.org/gist/rsignell-usgs/047235496029529585cc

Closing....
