### ISSUE TITLE
problems with big endian DataArrays

### ISSUE THREAD

**Issue by rabernat** [xray/xray#489]
I have some [MITgcm](http://mitgcm.org/) data in a [custom binary format](http://mitgcm.org/public/r2_manual/latest/online_documents/node277.html) that I am trying to wedge into xray. I found that DataArray does not know how to handle big endian datatypes, at least on my system.

```python
x = xray.DataArray( np.ones(10, dtype='>f4'))
print float(x.sum()), x.data.sum()
```
result:
```
4.60060298822e-40 10.0
```

**Comment by shoyer** [comment]
Do have bottleneck installed?

I've seen error messages from summing big endian arrays before, but never silently wrong results.

We resolved many of these issues for netcdf3 files by coercing arrays to little endian upon reading them from disk. We might even extend this to all arrays loaded into xray.

**Comment by rabernat** [comment]
I apparently do have bottleneck installed, although I was unaware of it until now. What is the relationship between bottleneck and this issue?

**Comment by shoyer** [comment]
This is a bug in bottleneck: https://github.com/kwgoodman/bottleneck/issues/104

You can work around this issue for now by uninstalling bottleneck. This will have a slight performance cost for little endian arrays, but it shouldn't be a big deal.

I'll also add a check to ensure we never try to pass big endian arrays to bottleneck.

**Comment by rabernat** [comment]
Thanks for looking into it.
In the meantime, I decided try writing a custom backend for my data instead.
