### ISSUE TITLE
64-bit values are coerced to 32-bit when writing as NETCDF4_CLASSIC

### ISSUE THREAD

**Issue by petercable** [xray/xray#526]
```
import xray
import numpy

ds = xray.Dataset()
time_data = numpy.arange(10.0, 100.0, .5)
raw_data = time_data.copy()
times = xray.Variable('time', time_data)
data = xray.DataArray(raw_data, dims=['time'], coords={'time': times})
ds['data'] = data
```

If you examine ds now, you’ll see:

```
<xray.Dataset>
Dimensions:  (time: 180)
Coordinates:
  * time     (time) float64 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 ...
Data variables:
    data     (time) float64 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 ...
```

Now, if we dump to netcdf and reload:

```
ds.to_netcdf('test1.nc', format='NETCDF4_CLASSIC')
ds1 = xray.open_dataset('test1.nc')
```

The formerly 64-bit values are now 32-bit:

```
<xray.Dataset>
Dimensions:  (time: 180)
Coordinates:
  * time     (time) float32 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 ...
Data variables:
    data     (time) float32 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 ...
```

It looks to me like coerce_nc3_dtype is being called for all formats that aren't straight NETCDF4.

**Comment by shoyer** [comment]
Indeed, it looks like netCDF4_classic can handle 64-bit variables. I misunderstand the description of that file format.

I think your diagnosis about the issue here is correct. Any interest in putting together a fix?

**Comment by petercable** [comment]
Sure, I'll take a look at it tonight if I get a chance. Do you need corresponding unit tests for any changes? I haven't looked...

**Comment by shoyer** [comment]
Yes, we would need a unit test to verify the change. It could be as simple as writing a file to disk as NETCDF4_CLASSIC and verifying that the dtype is preserved when it's read back.

**Comment by petercable** [comment]
I did some more investigating while working on a fix for this issue. It turns out that only the F8 format is supported and this fix is applicable to all NETCDF3-compatible formats.

https://www.unidata.ucar.edu/software/netcdf/docs/netcdf-c/NetCDF_002d3-Variable-Types.html

Type | C #define | Bits
---- | ---------- | -----
byte | NC_BYTE | 8
char | NC_CHAR | 8
short | NC_SHORT | 16
int | NC_INT | 32
float | NC_FLOAT | 32
double | NC_DOUBLE | 64

**Comment by shoyer** [comment]
Fixed by https://github.com/xray/xray/pull/529
