### ISSUE TITLE
Plot title variable too long

### ISSUE THREAD

**Issue by clarkfitzg** [xray/xray#534]
Current behavior:

```
air0 = airtemp.air.isel(time=0)
air0.plot()
```
![image](https://cloud.githubusercontent.com/assets/5356122/9316379/8c87fe28-44e9-11e5-82d8-81389118760d.png)

Preferred behavior:

![image](https://cloud.githubusercontent.com/assets/5356122/9316510/50f97052-44ea-11e5-9b72-195d20d53111.png)

Currently the plot titles are truncated at 50 characters using `DataArray._title_for_slice(self, truncate=50)`. To implement the new behavior we can just make this become `DataArray._title_for_slice(self, truncate=50, each=10)` which will additionally truncate each variable at 10 characters. This works well for dates.

For discussion- Do we add something indicating the variable was truncated? Like trailing ellipsis: `time = 2012-12-31...`

**Comment by shoyer** [comment]
I would suggest reusing `format_item` from `xray.core.formatting`, which provides such a nice summary for datetimes.

**Comment by clarkfitzg** [comment]
nice- I had forgotten about those

**Comment by rabernat** [comment]
:+1:  I just encountered this same problem.
