### ISSUE TITLE
xray.plot.contour doesn't handle colors kwarg correctly

### ISSUE THREAD

**Issue by rabernat** [xray/xray#537]
I found this while playing around with the plotting functions. (Really nice work btw @clarkfitzg!) I know the plotting is still under heavy development, but I thought I would share this issue anyway. I might take a crack at fixing it myself...

The goal is to make an unfilled contour plot with no colors. In matplotlib this is easy
```python
x, y = np.arange(20), np.arange(20)
xx, yy = np.meshgrid(x, y)
f = np.sqrt(xx**2 + yy**2)
plt.contour(x, y, f, colors='k')
```

If I try the same thing in dask
```python
da = xray.DataArray(f, coords={'y': y, 'x': x})
plt.figure()
xray.plot.contour(da, colors='k')
```
I get ```ValueError: Either colors or cmap must be None```.

I can't find any way around this (e.g. adding a ```cmap=None``` argument has no effect). If I remove the colors keyword, it works and makes colored contours, as expected.

I think this could be fixed easily if you agree it is a bug...

**Comment by shoyer** [comment]
Agreed, this seems like something we should fix. Help would definitely be appreciated!

**Comment by clarkfitzg** [comment]
@rabernat Thanks!
