### ISSUE TITLE
writing DataArray with 2D datetime variable doesn't work

### ISSUE THREAD

**Issue by andreas-h** [xray/xray#541]
On xray 0.5.1, writing a *Dataset* with a non-1D-datetime variable to netCDF doesn't work:

    times = xray.DataArray([[datetime.datetime.now()] * 2])
    print times
    <xray.DataArray (dim_0: 1, dim_1: 2)>
    array([['2015-08-19T14:27:50.911502000+0200',
            '2015-08-19T14:27:50.911502000+0200']], dtype='datetime64[ns]')
    Coordinates:
      * dim_0    (dim_0) int64 0
      * dim_1    (dim_1) int64 0 1

    times.to_dataset().to_netcdf('test.nc')

raises

    TypeError: Cannot convert input to Timestamp

**Comment by clarkfitzg** [comment]
Thanks for the report. This example indeed fails in 0.5.1, but it works in 0.5.2.

There's a fix documented in the latest release, but it doesn't reference a bug report- http://xray.readthedocs.org/en/stable/whats-new.html#bug-fixes
