### ISSUE TITLE
Dataset.to_dataframe() loses datetime64 timezone localization

### ISSUE THREAD

**Issue by IamJeffG** [xray/xray#552]
Not sure if feature or bug, but definitely made me look twice.

    >>> ds = xray.Dataset({'time': (['time'], [np.datetime64('2014-04-26T05:00:00-0700')])})
    >>> ds.time.values[0]
    numpy.datetime64('2014-04-26T05:00:00.000000000-0700')
    
    >>> ds.to_dataframe().index[0]
    Timestamp('2014-04-26 12:00:00')

I'd expected to see the DataFrame index maintaining its local timezone info:

    Timestamp('2014-04-26 05:00:00-0700', tz='America/Los_Angeles')

That said, the UTC that I actually get back is the same time so math should still work.  I'm opening this issue mostly as a matter for discussion -- feel free to close if you think xray should be pushing users towards UTC.

**Comment by jhamman** [comment]
Is this just the pandas `repr` behavior?

**Comment by shoyer** [comment]
Xray relies on numpy's datetime64 dtype, which for better or worse does not store timezone. Pandas creates its own array type (wrapping numpy) to make timezone localization work properly, but I don't want to go to those lengths in xray. So I'm happy to push users to UTC for now, and wait until upstream improvements make it easier to customize array dtypes (for things like datetime types with timezones).
