### ISSUE TITLE
operation on complex number data

### ISSUE THREAD

**Issue by davidtrem** [xray/xray#553]
Hello,

Would it be possible to add complex function operation on xray.DataArray ?

Function like np.sin, np.abs works properly on xray.DataArray containing complex numbers and
returns a DataArray (as expected).
However, np.real, np.imag, np.angle operation return an numpy.ndarray array instead of DataArray...

**Comment by davidtrem** [comment]
A short example for convenience:
```python
import xray
import numpy as np
arr = xray.DataArray(np.random.randn(2, 3) + 1j*np.random.randn(2, 3))
np.abs(arr)  # returns a xray DataArray
np.angle(arr)  # returns a numpy ndarray 
```

**Comment by davidtrem** [comment]
I realized this is also an issue for Pandas so I also reported here:
https://github.com/pydata/pandas/issues/10921

**Comment by shoyer** [comment]
There's nothing we can do about `np.angle`, `np.real` and `np.imag` unfortunately -- these need to be updated on the numpy side to call `__array_wrap__`.

However, we could certainly add `.real` and `.imag` properties that access these computed values as DataArrays.

**Comment by davidtrem** [comment]
That would be great to add `.real` and `.imag` :+1:

**Comment by shoyer** [comment]
You can also use `xarray.ufuncs.angle()` for this.

**Comment by rth** [comment]
@shoyer Aww, great. Thanks for pointing this out.

**Comment by NotSqrt** [comment]
@shoyer xarray.ufuncs.angle now triggers the DeprecationWarning added in #1962, and numpy/numpy#6266 is still open.

What is the recommended way to keep an DataArray when computing angles ?

Thanks !

**Comment by shoyer** [comment]
The short answer is that we shouldn't remove `xarray.ufuncs.angle` until NumPy has a satisfactory overload mechanism for it. This might mean something like http://www.numpy.org/neps/nep-0018-array-function-protocol.html instead.

`PendingDeprecationWarning` is the weakest form of deprecation warning. Basically it means "We plan to deprecate it in the future, but haven't done so yet."

**Comment by NotSqrt** [comment]
Thanks !
