### ISSUE TITLE
replace time coordinates for whole year

### ISSUE THREAD

**Issue by mathause** [xray/xray#560]
It is quite convenient to select a whole year `ds.sel(time='1991')`. However, sel should not be used to assign data. Thus you can not do `ds.sel(time='1991').coords['time'] = time` and `ds[dict(time='1991')] ` does not work.

1) Should `ds[dict(time='1991')] ` work?

2) A possible workaround is:
    
    idx = xray.core.indexing.remap_label_indexers(ds, {'time' : '1999'})
    ds[idx] = time

Should this be added to the documentation or is this case too uncommon?

**Comment by mathause** [comment]
Ok, I just saw that this `ds.sel(time='1991').coords['time'] = time` does not work anyways. But I guess the questions remains still valid.

**Comment by shoyer** [comment]
You can do label based assignment with `ds.loc[dict(time='1991')] = ...`. Any argument to `ds[...]` are assumed to be positional, even if you use a name for the dimension.

**Comment by mathause** [comment]
Ok, thanks.
