### ISSUE TITLE
to_netcdf() writes attrs as unicode strings 

### ISSUE THREAD

**Issue by chrwerner** [xray/xray#564]
Hi.

Seems like xray writes attributes as unicode strings to netcdf files. This causes problems with other software. The attrs show up as "string ..." with ncdump for instance and ncview does not recognise the units attributes etc.

For the moment I do this:
<code>nc.attrs = OrderedDict( (str(k),str(v)) for k,v in nc1_backup.attrs.iteritems() ) </code>

**Comment by shoyer** [comment]
I think this is actually an upstream change in netcdf4-Python rather anything we did in xray: https://github.com/Unidata/netcdf4-python/issues/388

One simple work around is to explicitly write an older version of the netcdf file format by using the format argument.

**Comment by chrwerner** [comment]
Ah, ok... Thanks.
