### ISSUE TITLE
dim_names, coord_names, var_names, attr_names convenience functions

### ISSUE THREAD

**Issue by naught101** [xray/xray#582]
It'd be nice to have some convenience functions for easy outout of dim/coord/variable/attr names, eg:

```python
ds.dim_names() == list(ds.dims.keys())
ds.coord_names() == list(ds.coords.keys())
ds.var_names() == list(ds.vars.keys())
ds.attr_names() == list(ds.attrs.keys())
```

just for reading/writing sanity.

**Comment by shoyer** [comment]
All of these are dictionaries (on `Dataset` objects), so you can simply write `list(ds.dims)` or `ds.dims.keys()` if you want to be more explicit. That's not any more characters than `ds.dim_names()`, so I'm not sure if there's much of an advantage to it.

**Comment by clarkfitzg** [comment]
`Dataset` currently has around 100 attributes. It would be nice to keep this manageable.

**Comment by naught101** [comment]
Fair enough, I wasn't aware `list(ds.dims)` worked..

`.keys()` returns a keys though, not a list:

```python
In [4]: ds.dims.keys()
Out[4]: KeysView(Frozen(SortedKeysDict({'time': 70128, 'z': 1, 'x': 1, 'y': 1})))

In [5]: ds.dims.keys()[0]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-874ed46e2639> in <module>()
----> 1 ds.dims.keys()[0]

TypeError: 'KeysView' object does not support indexing
```
