### ISSUE TITLE
Bug when accessing sorted dataset before loading

### ISSUE THREAD

**Issue by jhamman** [xray/xray#593]
I ran into this bug this afternoon.  If I sort a Dataset using `isel` before loading the data, I end up with an error in the `netCDF4` backend. If I call `Dataset.load()` before sorting the Dataset, I get the expected behavior.

First some info on my environment (everything should be fresh):
```
Python version  :  3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41) 
[GCC 4.2.1 (Apple Inc. build 5577)]
xray version    :  0.6.0
numpy version   :  1.9.3
netCDF4 version :  1.1.9
```

Now for a simplified example that reproduces the bug:

```Python

In [1]: 
import xray
import numpy as np
import netCDF4

In [2]:
random_data = np.random.random(size=(4, 6))
dim0 = [0, 1, 2, 3]
dim1 = [0, 2, 1, 3, 5, 4]  # We will sort this in a later step
da = xray.DataArray(data=random_data, dims=('dim0', 'dim1'),
                    coords={'dim0': dim0, 'dim1': dim1}, name='randovar')
ds = da.to_dataset()
ds.to_netcdf('rando.nc')

In [3]:
ds2 = xray.open_dataset('rando.nc')
# ds2.load()  # work around to prevent IndexError
inds = np.argsort(ds2.dim1.values)
ds2 = ds2.isel(dim1=inds)
print(ds2.randovar)

Out[3]:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-9b4ab63c0fd2> in <module>()
      2 inds = np.argsort(ds2.dim1.values)
      3 ds2 = ds2.isel(dim1=inds)
----> 4 print(ds2.randovar)

...

/Users/jhamman/anaconda/lib/python3.4/site-packages/xray/backends/netCDF4_.py in __getitem__(self, key)
     43         else:
     44             getitem = operator.getitem
---> 45         data = getitem(self.array, key)
     46         if self.ndim == 0:
     47             # work around for netCDF4-python's broken handling of 0-d

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:30994)()

/Users/jhamman/anaconda/lib/python3.4/site-packages/netCDF4/utils.py in _StartCountStride(elem, shape, dimensions, grp, datashape, put)
    220                 # duplicate indices in the sequence)
    221                 msg = "integer sequences in slices must be sorted and cannot have duplicates"
--> 222                 raise IndexError(msg)
    223             # convert to boolean array.
    224             # if unlim, let boolean array be longer than current dimension

IndexError: integer sequences in slices must be sorted and cannot have duplicates
```

**Comment by shoyer** [comment]
We could work around this, but this is arguably a bug/limitation of netCDF4 Python, which no longer allows indexing with unsorted integer sequences. See https://github.com/Unidata/netcdf4-python/issues/300 and https://github.com/Unidata/netcdf4-python/pull/308.

I think this could probably be fixed upstream somewhat straightforwardly by canonicalizing indexers as integer arrays instead of as boolean arrays. I'm not sure what we can do about it here.

**Comment by jhamman** [comment]
That makes sense.  I agree that this is ultimately a `netCDF4` limitation.

So moving forward, we could one or more of the following:

1. Fix this in `netCDF4`, allowing unsorted integer arrays as indexers.
2. Check in `isel` that the indexer is valid when the data is still sitting on disk.  Raise an `IndexError` in the cases that will fail later on.
3.  Ugly: In cases where `isel` is provided with unsorted integer arrays, we could force the data to be loaded.
4.  Uglier: Somehow store the integer array mapping in `xray`, using `netCDF4` as is, and returning a view after the data has been loaded. 

In my view, the current behavior of `isel` is failing silently and this is not what we want.

**Comment by shoyer** [comment]
My vote would be for catching and re-raising the error with a more informative message. Something like:
```
IndexError: the indexing operation you are attempting to perform is not
valid on netCDF4.Variable object. Try loading your data into memory
first by calling .load().

Original traceback:
...
```

This is automatic when you re-raise on Python 3. On Python 2, you'll have to use `traceback.format_exc()` to capture the traceback.

**Comment by jhamman** [comment]
I'm going to argue that it is better to raise an error at the time of offense.  Currently we are failing silently, and yielding objects that are unusable. The logic I'm envisioning is like this:
```
if not issorted(indexer) and not self.loaded:
    raise IndexError('...')
```

**Comment by shoyer** [comment]
I'm all behind that error message in principle, but it needs to be specific to the netcdf4 backend. For example, this works perfectly fine with scipy. Given these constraints, especially given that either of these arrays may be triggered lazily by a dask.array, I think this will be difficult to solve at all times when the expression is written.

**Comment by jhamman** [comment]
Okay then, I think it makes sense to re-raise as you originally suggested.  I'll put together a PR tomorrow.
