### ISSUE TITLE
scikit-xray vs xray

### ISSUE THREAD

**Issue by hainm** [xray/xray#599]
FYI: it's likely there will be confusion in the future.

https://github.com/scikit-xray

**Comment by shoyer** [comment]
Yep, we've been considering renaming this package, though nothing has been decided yet. It's possibly worth adding an entry to the FAQ in the meanwhile.

**Comment by hainm** [comment]
>  we've been considering renaming this package

so I guess you should rename before it's too late. :P

**Comment by shoyer** [comment]
Too late for what? :)

**Comment by hainm** [comment]
To rename. :p
