### ISSUE TITLE
latest docs are broken

### ISSUE THREAD

**Issue by jhamman** [xray/xray#602]
Looking at the doc build from tonight, something happened and netCDF4 isn't getting picked up.  All the docs depending on the netCDF4 package are broken (e.g. plotting, IO, etc.).

@shoyer - You may be able to just resubmit the doc build, or maybe we need to fix something.

**Comment by shoyer** [comment]
Hmm. We don't run netcdf4 in the docs because we can't install the netcdf binaries on readthedocs. I'll take a look though.

**Comment by shoyer** [comment]
This is a new issue with ReadTheDocs: https://github.com/rtfd/readthedocs.org/issues/1726

**Comment by shoyer** [comment]
Conda support for ReadTheDocs is finally in sight! https://github.com/rtfd/readthedocs.org/issues/857

Hopefully that will take care of our troubles here

**Comment by jhamman** [comment]
@shoyer - It looks like Conda support has been deployed at readthedocs now.  Have you tried getting the xray docs to build there yet?
