### ISSUE TITLE
support using Cartopy with facet grids

### ISSUE THREAD

**Issue by jhamman** [xray/xray#603]
Currently, I don't think it is possible to specify a Cartopy projection for facet grid plots.  

It would be nice to be able to specify either the subplots array including Cartopy projections (e.g. `ax=axes`) or a projection key word argument via (`subplots_kw=dict(projection=...)`) directly when using the xray's facet grid.

**Comment by shoyer** [comment]
:+1: I got this working with Seaborn's FacetGrid, so it should be pretty straightforward to port to xray. That's what this example is all about:
http://stanford.edu/~mwaskom/software/seaborn/examples/facets_with_custom_projection.html

(The example there doesn't use cartopy to avoid a build dependency.)
