### ISSUE TITLE
operations with pd.to_timedelta() now fails

### ISSUE THREAD

**Issue by WeatherGod** [xray/xray#615]
Not exactly sure when this started to fail, but I recently upgraded my pandas install and a script of mine started to fail. The SSCCE:
```
from datetime import datetime, timedelta
import xray
import pandas as pd

a = xray.Dataset({'time': [datetime(2000, 1, 1)]})
a['time'] -= pd.to_timedelta(timedelta(hours=6))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/xray-0.6.0_154_gf270b9f-py2.7.egg/xray/core/dataarray.py", line 1091, in func
    f(self.variable, other_variable)
  File "/nas/home/broot/centos6/lib/python2.7/site-packages/xray-0.6.0_154_gf270b9f-py2.7.egg/xray/core/variable.py", line 799, in func
    self.values = f(self_data, other_data)
TypeError: ufunc subtract cannot use operands with types dtype('<M8[ns]') and dtype('O')
```
Perhaps it makes sense to create a new xray convenience method like pandas's "to_timedelta()" that returns numpy arrays of timedelta64 instead of pandas's special timedelta objects? Or to somehow cast these objects appropriately on the fly?

My current workaround is the following:
```
import numpy as np
a['time'] -= np.array([6], dtype='timedelta64[h]')
```
While that particular form isn't terrible, it gets very awkward if my timedelta is a combination of different units like 3 hours and 15 minutes or something odd like that.

**Comment by jhamman** [comment]
Do you have to use `pd.to_timedelta()`?  This seems to work:

```Python
a = xray.Dataset({'time': [datetime(2000, 1, 1)]})
a['time'] -= np.timedelta64(timedelta(hours=6))
```

**Comment by WeatherGod** [comment]
hmm, good point. I wish I knew why I ended up using `pd.to_timedelta()` in the first place. Did numpy not support converting timedelta objects at one point?

**Comment by shoyer** [comment]
`pandas.Timedelta` has a `to_timedelta64()` method that you also use to do the coercion.

The reason why this broke is that pandas used to return `numpy.timedelta64` objects, but then added the `Timedelta` type (a few versions ago) and switched over to that.

I agree that it would be nice to support this sort of conversion automatically. I opened a new issue for that (#616).
