### ISSUE TITLE
Best way to copy data layout?

### ISSUE THREAD

**Issue by naught101** [xray/xray#625]
I have a dataset that represents some observed variables at a particular site.

For example:

```python
<xray.Dataset>
Dimensions:           (time: 70128, x: 1, y: 1, z: 1)
Coordinates:
  * x                 (x) float64 1.0
  * y                 (y) float64 1.0
  * time              (time) datetime64[ns] 2003-01-01T00:30:00 ...
  * z                 (z) float64 1.0
Data variables:
    latitude          (y, x) float64 41.9
    longitude         (y, x) float64 13.61
    SWdown            (time, y, x) float64 0.0 0.01205 0.0 0.0 0.0 0.0 0.0 ...
    Tair              (time, z, y, x) float64 276.8 276.4 276.4 276.7 276.7 ...
    Rainf             (time, y, x) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    elevation         (y, x) float64 884.2
    reference_height  (y, x) float64 4.0
Attributes:
    Production_time: 2012-09-27 11:34:52
    Production_source: ...
```

I want to use this data as input to a model, and then output a data structure that is the same, except that it contains different output variables.

I tried doing

```python
new_ds = old_ds[['latitude', 'longitude', 'elevation', 'reference height']]
```

and then adding the new variables, but this drops the time coordinate, so you have to re-create it manually. Is there a better way? It would be quite nice if it was possible to do something like 

```python
new_ds = old_ds[vars, drop_coords=False]
```

**Comment by naught101** [comment]
Hrm, I guess I can just do

```python
new_ds = old_ds[GEO_VARS]
for c in old_ds.coords:
    if c not in new_ds.coords:
        new_ds.coords[c] = old_ds.coords[c]
```

Still, it might be nice to have this built in.

**Comment by shoyer** [comment]
I think the preferred way to do this would be to set `['latitude', 'longitude', 'elevation', 'reference_height']` as coordinates on the dataset, e.g., using the `set_coords` method. Then you can simply pass the `.coords` to the Dataset or DataArray constructor, e.g., `new_ds = xray.Dataset(coords=old_ds.coords)` or `new_array = xray.DataArray(values, dims=('x', 'y', z', 'time'), coords=old_ds.coords)`.

**Comment by naught101** [comment]
The lat/x, long/y is a bit odd, yeah, I think the file is set up a bit wrong, but I'm trying to stick to the format I'm given.

Reference height, at least, isn't really a co-ordinate. It's the value of the tower measurements. The other data is really (implicitly) at elevation+screen height, I think. 

But yeah, that's basically what I came up with, just copy the relevant coords for each variable from the old dataset.
