### ISSUE TITLE
Unexpected behavior by diff when applied to coordinate DataArray

### ISSUE THREAD

**Issue by spencerahill** [xray/xray#634]
`DataArray.diff`, when applied to a coordinate, just returns the coordinate itself with one index truncated.  Consider the following:
```
In [5]: arr = xray.DataArray(range(0, 20, 2), dims=['lon'], coords=[range(10)])
In [6]: arr.diff('lon')
<xray.DataArray (lon: 9)>
array([2, 2, 2, 2, 2, 2, 2, 2, 2])
Coordinates:
  * lon      (lon) int64 1 2 3 4 5 6 7 8 9

In [7]: arr['lon'].diff('lon')
<xray.DataArray 'lon' (lon: 9)>
array([1, 2, 3, 4, 5, 6, 7, 8, 9])
Coordinates:
  * lon      (lon) int64 1 2 3 4 5 6 7 8 9
```

Is this the intended behavior?  The documentation doesn't mention anything about this, and its counter-intuitive, so I'm wondering if its a bug instead.  Even if it is intended, I personally would like to be able to use a coordinate array's diff on itself to get its spacing, e.g. for use as the denominator in finite differencing approximations to derivatives.

Thanks!

**Comment by shoyer** [comment]
Thanks for the report -- this is definitely a bug. I think the solution here is similar to the refactoring we need to support accessors like `ds['time.time']`:
https://github.com/xray/xray/issues/367

**Comment by spencerahill** [comment]
Cool, thanks.  Not familiar enough w/ the xray source code at this time to contribute directly to the refactor, but for the time being here's a simple 2-liner workaround:
```python
dlon = arr['lon'].diff('lon')
dlon.values = np.diff(arr['lon'])
```

**Comment by shoyer** [comment]
Yeah, I think I need to tackle this one -- it will be a little messy. I have a work in progress branch I can finish up.
