### ISSUE TITLE
time slice cannot be list 

### ISSUE THREAD

**Issue by rafa-guedes** [xray/xray#660]
Not sure this is a problem or expected behaviour. When slicing a variable from dataset using sel() method, if I only want one time, the time slice cannot be in a list (in my case, it failed when level slice had more than one value). However, with a scalar float, it works. Please see example below where I try to slice from CFSR currents file.

This does not work:
---
```
dset['uo'].sel(latitude=-49, longitude=162.75, lev=[0,100,1000], time=[1.41747840e+09], method='nearest')
```
*** IndexError: The indexing operation you are attempting to perform is not valid on netCDF4.Variable object. Try loading your data into memory first by calling .load().

Original traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/xray-0.6.1_15_g5109f4f-py2.7.egg/xray/backends/netCDF4_.py", line 47, in __getitem__
    data = getitem(self.array, key)
  File "netCDF4.pyx", line 2991, in netCDF4.Variable.__getitem__ (netCDF4.c:36676)
  File "/usr/lib64/python2.7/site-packages/netCDF4_utils.py", line 245, in _StartCountStride
    raise IndexError("Indice mismatch. Indices must have the same length.")
IndexError: Indice mismatch. Indices must have the same length.

This works:
---
```
dset['uo'].sel(latitude=-49, longitude=162.75, lev=[0,100,1000], time=1.41747840e+09, method='nearest')
```
<xray.DataArray 'uo' (lev: 3)>
array([ 0.024,  0.012,  -0.008])
Coordinates:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;latitude   float64 -48.75
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lev        (lev) float64 5.0 105.0 949.0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;longitude  float64 162.8
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;time       float64 1.417e+09
Attributes:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;short_name: uo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;long_name: U-Component of Current
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;level: Depth below sea surface
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;units: m/s

**Comment by shoyer** [comment]
@rafa-guedes is this issue also fixed by upgrading netCDF4-python?

**Comment by rafa-guedes** [comment]
Yes it is @shoyer !

**Comment by shoyer** [comment]
awesome -- glad that worked!
