### ISSUE TITLE
"weird" plot

### ISSUE THREAD

**Issue by hainm** [xray/xray#663]
IMO, this is "weird" plot that triggers imagination. 

http://xray.readthedocs.org/en/stable/_images/2d_simple.png

**Comment by naught101** [comment]
and?

**Comment by jhamman** [comment]
@hainm - What is weird about this plot?  Would you like to suggest a way that this plot could be improved?  Otherwise, I'm going to close this issue.

**Comment by hainm** [comment]
Hi

It seems that I am only one having dirty mind, so I am closing this.

**Comment by MaximilianR** [comment]
I agreed with you @hainm!
