### ISSUE TITLE
Making xray use multiple cores

### ISSUE THREAD

**Issue by JoyMonteiro** [xray/xray#672]
Hello,

I was trying out the 'chunks' argument to open dataset so that I could use
the out-of-core functionality. It works very well, but when I run top I see only
one core being utilised. Is there some argument I need to pass to make
it use more cores?

TIA,
Joy

**Comment by shoyer** [comment]
What sort of computation are you doing? Some tasks are limited to a single core, notably reading netCDF4 files with in-file compression. Dask's [profiler](http://dask.pydata.org/en/latest/diagnostics.html#profiler) may be helpful here.

**Comment by JoyMonteiro** [comment]
I was trying to read ERA-Interim data, calculate anomalies using ds = ds - ds.mean(dim='longitude'), and similar operations along the time axis. Are such operations restricted to single cores?

Just multiplying two datasets (u*v) seems to be faster, though top shows two cores being used (I have 4 physical cores).

TIA,
Joy

**Comment by JoyMonteiro** [comment]
Hello, I ran it with the dask profiler, and I looked at the top output disaggregated by core.
It does seem to use multiple cores, but it seems to be using 8 threads when I looked at prof.visualize() (hyperthreading :P) and I feel this is killing performance.

How can I control how many threads to use?

Thanks,
Joy

**Comment by shoyer** [comment]
Those sorts of operations should be easily parallelized, although depending on what you're doing with the data they might also be IO bound. It's worth experimenting with chunk sizes. For control on the number of threads, see his page: http://dask.pydata.org/en/latest/scheduler-overview.html#configuring-the-schedulers

**Comment by JoyMonteiro** [comment]
You were right, my chunk sizes were too large. It did not matter how many threads dask used either (4 vs. 8). The I/O component is still high, but that is also because I'm writing the final computed DataArray to disk.

Thanks!
