### ISSUE TITLE
resampling with missing data

### ISSUE THREAD

**Issue by slharris** [xray/xray#673]
I regularly use resample and groupby to analyse a 40 year hourly 2D dataset with no problems. However, a new dataset that I am working with is missing some leap year days and the output is wrong with what seems like months have been swapped around. Is this because the number of days in the month is used to divide to get the mean? 
So my actual question is - how is the mean taken when using groupby or resample, does it count the number hours or days in the dataset and how does it deal with missing data?

Some of the steps I follow:
```Python
ds=xray.open_mfdataset(filepath)    
dsvariable=ds[variable]
resampledaily=(dsvariable.resample('D', dim='time', how='max'))
resamplemonthly=(resampledaily.resample('1MS', dim='time', how='mean'))
monthly_ts=resamplemonthly.groupby('time').mean()
```

**Comment by shoyer** [comment]
> how is the mean taken when using groupby or resample, does it count the number hours or days in the dataset and how does it deal with missing data?

Xray using dask/numpy's `nanmean`, which skips over NaN values, including them neither in the count of elements nor the sum (the mean is given by the sum divided by the count). It's similar for `nanmax`. So to answer your question, it should count the actual number of hours in the dataset with non-NaN values. Neither resample nor groupby have any *a priori* knowledge of the number of elements in a group beyond what they see in the data.

There have been some related dask.array bugs that we've squashed over the past few months (in particular [for `nanmax`](https://github.com/blaze/dask/pull/776)), so I would make sure that you're running the latest release of dask.array. But if that doesn't fix things, a more detailed report would help!

**Comment by slharris** [comment]
Updating with the latest release of dask.array fixed it! Thank you so much for responding!
