### ISSUE TITLE
Is 'name' an xray supported attribute? 

### ISSUE THREAD

**Issue by MaximilianR** [xray/xray#679]
If it is, a Dataset constructor should take a list of DataArrays, and use their names as keys? (and anywhere else you need to provide a dict-like mapping with names)

If it's not, we potentially shouldn't be using it in the internals.

I think it's the first, given it's in the [docs](http://xray.readthedocs.org/en/stable/generated/xray.DataArray.name.html) (although not [throughout](http://xray.readthedocs.org/en/stable/data-structures.html#dataarray) the docs).

**Comment by shoyer** [comment]
`DataArray.name` is a valid attribute -- it's filled in with the key corresponding to DataArrays in Datasets. `Dataset.name` is not valid. This is analogous to the situation on `DataFrame` and `Series`.

Converting a list of DataArrays into a Dataset does sound like a useful thing, but to me that functionality is would be a closer fit for a hypothetical `merge` function (#417). I was envisioning as taking a list of Dataset objects, but it would be straightforward to merge in `DataArray` objects, too.

**Comment by MaximilianR** [comment]
Great, that's clear, cheers @shoyer
