### ISSUE TITLE
to_masked_array should have an option to always return array

### ISSUE THREAD

**Issue by femtotrader** [xray/xray#684]
Hello,

I'm working with Monary and xray and faced a problem because `xray.DataArray.to_masked_array` doesn't return an array of boolean but just a boolean.

```
In [1]: ma.masked_array(df['Bid'].values, df['Bid'].isnull())
Out[1]:
masked_array(data = [0.81 0.88805 0.8880899999999999 ..., 0.87531 0.87531 0.87531],
             mask = [False False False ..., False False False],
       fill_value = 1e+20)

In [2]: ds.Bid.to_masked_array()
Out[2]:
masked_array(data = [ 0.81     0.88805  0.88809 ...,  0.87531  0.87531  0.87531],
             mask = False,
       fill_value = 1e+20)
```

So we have

    mask = False,

instead of

    mask = [False False False ..., False False False],

It will be nice if a parameter could be passed to always return array.

Here is my code
With sample data from https://drive.google.com/file/d/0B8iUtWjZOTqla3ZZTC1FS0pkZXc/view?usp=sharing

```
import pandas as pd
import xray
df = pd.read_csv("AUDUSD-2014-01.csv", names=['Symbol', 'Date', 'Bid', 'Ask'])
df['Date'] = pd.to_datetime(df['Date'], format='%Y%m%d %H:%M:%S.%f')
ds = xray.Dataset.from_dataframe(df)
ds = ds[['Bid', 'Ask']]
lst_cols = list(map(lambda col: ds[col].to_masked_array(), ds.data_vars))
mparams = monary.MonaryParam.from_lists(lst_cols, list(ds.data_vars), ['float64', 'float64'])
m.insert('monary_db', 'ticks', mparams)
```

It raises

```
//anaconda/lib/python3.4/site-packages/monary/monary.py in insert(self, db, coll, params, write_concern)
    763             for i, param in enumerate(params):
    764                 data_p = param.array.data.ctypes.data_as(ctypes.c_void_p)
--> 765                 mask_p = param.array.mask.ctypes.data_as(ctypes.c_void_p)
    766
    767                 if cmonary.monary_set_column_item(

AttributeError: 'numpy.bool_' object has no attribute 'ctypes'
```

see `lst_cols`

```
[masked_array(data = [ 0.88796  0.88805  0.88809 ...,  0.87531  0.87531  0.87531],
              mask = False,
        fill_value = 1e+20),
 masked_array(data = [ 0.88922  0.88914  0.8891  ...,  0.87588  0.87574  0.87574],
              mask = False,
        fill_value = 1e+20)]
```

An other option could be to fix this on Monary side
https://bitbucket.org/djcbeach/monary/issues/22/insert-doesnt-work-correctly-when-mask-is

Kind regards

**Comment by shoyer** [comment]
Hmm. We currently use `np.ma.masked_where` to construct a masked array, which sometimes creates masked arrays with as a scalar mask (`mask=False`):
```
>>> np.ma.masked_where(np.arange(3) < -10, np.arange(3))
masked_array(data = [0 1 2],
             mask = False,
       fill_value = 999999)
```

I'm not entirely sure if these are actually valid masked arrays or not (maybe @jhamman or someone who uses masked arrays more often than me would know?), but I agree that it's not very useful for xray to return them. An alternative would be to use the `MaskedArray` constructor, which does not have this issue:
```
>>> np.ma.MaskedArray(np.arange(3), np.arange(3) < -10)
masked_array(data = [0 1 2],
             mask = [False False False],
       fill_value = 999999)
```

This seems like better behavior to me.

If you're interested in putting together a fix, here's the relevant place in xray:
https://github.com/xray/xray/blob/1c908bebff4c621c959d1bc8f78b4e4298ee87ce/xray/core/dataarray.py#L993
