### ISSUE TITLE
Dataset.T property creates conflict with data named 'T'

### ISSUE THREAD

**Issue by brian-rose** [xray/xray#687]
I frequently find myself working with datasets that include a variable named `'T'` (for temperature!)

The problem with this is that, unlike any other variable, `mydataset.T` does not return the variable, because there is a built-in property `.T` which is just a map to the `mydataset.transpose()` method.

This is mostly just a minor annoyance, because of course I can access the data as `mydataset['T']`, but it necessitates an odd asymmetry in any code that accesses `T` as well as other data. And, maybe more importantly, `mydataset.T` does NOT immediately raise an error in code that is attempting to access the temperature data.

I have not been able to simply remove the property interactively from the `dataset` objects, e.g.
`del mydataset.T`
raises an error
`AttributeError: can't delete attribute`

Since the transpose functionality is already easily accessible through `mydataset.transpose()` (which is more readable, in my opinion), perhaps the `T` property should just be removed?

**Comment by MaximilianR** [comment]
Removing `.T` would break so much existing code, I don't think that's going to get much support. It's also consistent with numpy.

If you use IPython, tab-complete will work, so if your column is called `temperature`, you can access it almost as quickly...

**Comment by jhamman** [comment]
Agreed, I don't think we want to get rid of the transpose method `T`.  A better solution for you would probably be to rename your temperature variable using the `rename` method.  I often do this when comparing multiple datasets that use different variable naming conventions.

**Comment by brian-rose** [comment]
Brilliant, somehow I missed the `rename` method in the documentation. Also, I missed the fact that `.T` is consistent with numpy. I will just make a habit of renaming all my variables called `T` from now on. Thanks for these comments.
