### ISSUE TITLE
Should Dataset enforce some ordering of dims in its variables?

### ISSUE THREAD

**Issue by MaximilianR** [xray/xray#689]
I'm not sure on this one. I'm currently having a bunch of issues with this sort of Dataset:
(notice the dims are `(d, c)` and `(c, d)` for different variables)
```python
<xray.Dataset>
Dimensions:               (c: 193, d: 6781)
Coordinates:
  * d                   (d) object 5218 5219 5220 5221 5222 5223 5224 ...
  * c       		 (c) object LDS. ...
    j       	         (c, d) bool False False False False ...
Data variables:
    r                  (d, c) float64 nan -0.05083 nan ...
    s                  (d, c) float64 nan -0.05083 nan ...
    n                  (c, d) float64 nan nan nan nan nan ...
```
In my case, this is particularly painful when passing the result of `ds.r.to_pandas()` into a function expecting a DataFrame with a certain orientation when that orientation isn't reliable.

Is this a problem generally?

If it is, I could imagine a few solutions - enforce ordering, offer a method on a DataSet to align the dims, offer a `kwarg` on `.to_pandas()` to allow specifying the dims-axis mapping, etc

**Comment by shoyer** [comment]
The easiest way to enforce that dimensions have a consistent order is to use the transpose method, e.g., `ds.transpose('c', 'd')`. Does that suffice? I'm not sure enforcing an ordering would be a good idea -- it makes the xray data model slightly less  flexible.

**Comment by MaximilianR** [comment]
Great, I didn't know `transpose` could do that, cheers.
FWIW this doesn't seem to enforce the ordering of the dims of coords in a DataArray - let me know if you want me to open an issue / post an example.

I think that makes sense re enforcing the ordering. I think my current use case is very specific (applying functions to pandas objects, which don't recognize `dim`s, and so fail if things are in the wrong order). More generally, I'd hope functions would be robust to the order of dimensions.

I'll close for now.

Thanks as ever!
